In [24]:
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, UpSampling2D
from tensorflow.keras import regularizers
import matplotlib.pyplot as plt
import numpy as np

### Defining a model using UpSampling2D -


In [25]:
# Sample input data
X = np.asarray([[1, 2],
			      [3, 4]])
# Reshape the data
X = X.reshape((1, 2, 2, 1))

# Define model
model = Sequential()
# Upsample the data by a factor of 2
model.add(UpSampling2D(input_shape=(2, 2, 1)))
model.summary()

scaled_data = model.predict(X)
scaled_data = yhat.reshape((4, 4))
print(f"\n{yhat}")

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_6 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]
